import { MdDevices } from "react-icons/md"
import { MdModeComment } from "react-icons/md"
import { MdAccountCircle } from "react-icons/md"

const Service = [
    { name: 'Basic', id: 0, price: 400, available: 10, logo: <MdAccountCircle />, route:"/pricing/Basic",descrp:"ADMINISTRACIÓN DE PERFILES EN REDES SOCIALES - 1 POSTEO SEMANAL EN HORARIOS DE ALTO TRÁFICO - RESPUESTA A COMENTARIOS E INTERACIONES EN INBOX, POSTS Y REVIEWS - SEGUIMIENTO A TRÁFICO, SEGUIDORES E INTERACCIONES POR REDES SOCIALES" },
    { name: 'Dev', id: 2, price: 800, available: 10, logo: <MdDevices />, route:"/pricing/Dev", descrp: "ADMINISTRACIÓN DE PERFILES EN REDES SOCIALES - 4 POSTEOS SEMANALES EN HORARIOS DE ALTO TRÁFICO - RESPUESTA A COMENTARIOS E INTERACIONES EN INBOX, POSTS Y REVIEWS - SEGUIMIENTO A TRÁFICO, SEGUIDORES E INTERACCIONES POR REDES SOCIALES ADMINISTRACIÓN DE CONTENIDO AUDIOVISUAL PARA POSTEO EN REDES - REDES INCLUÍDAS: PLAN SOCIAL + TWITTER + 4 STORIES DE INSTAGRAM - SEMANALES REPORTE MENSUAL DE COMPORTAMIENTO DE REDES SOCIALES- ANÁLISIS + PUESTA EN MARCHA + DINAMIZACIÓN + MANTENIMIENTO PERSONALIZADO - CREACION PROPUESTA DISEÑO DE PAGINA WEB - DESARROLLO Y SUBIDA DE PAGINA WEB (1-5 SECCIONES) - SEO BASICO - UN (1) MANTENIMIENTO MENSUAL POR EL PRIMER AÑO CON DKM"},
    { name: 'Social', id: 1, price: 500, available: 10, logo: <MdModeComment />, route:"/pricing/Social", descrp:"ADMINISTRACIÓN DE PERFILES EN REDES SOCIALES - 3 POSTEOS SEMANALES EN HORARIOS DE ALTO TRÁFICO - RESPUESTA A COMENTARIOS E INTERACIONES EN DM, POSTS Y REVIEWS - SEGUIMIENTO A TRÁFICO, SEGUIDORES E INTERACCIONES POR REDES SOCIALES - ADMINISTRACIÓN DE CONTENIDO AUDIOVISUAL PARA POSTEO EN REDES - REDES INCLUÍDAS: PLAN BASIC + INSTAGRAM, (NO INCLUYE STORIES) - REPORTE TRIMESTRAL DE COMPORTAMIENTO DE REDES SOCIALES" },
]

export default Service